- name: Debug Variable In Normal Playbook
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Show group_var
      debug:
        var: group_vars_val

    - name: Debug host_var
      debug:
        var: host_vars_val

    - name: Debug collection_var
      debug:
        var: collection_var
